# https://taskfile.dev

version: '3'

dotenv: ['.env']
silent: true

tasks:
  default:
    desc: prints this help
    cmd: task -l

  up:
    desc: starts docker compose
    cmd: docker compose -f docker-compose.yml up --build --watch
